services:
  db:
    image: postgres:16
    container_name: quickshop
    environment:
      POSTGRES_USER: quickshop
      POSTGRES_PASSWORD: quickshop
      POSTGRES_DB: quickshop
    ports:
      - "5432:5432"
    volumes:
      - ./fornitori.csv:/csv/fornitori.csv:ro
      - ./ordini.csv:/csv/ordini.csv:ro
